version: "3"

services:
  app:
    container_name: catch_dining_app
    image: ${DOCKERHUB_USERNAME}/catch-dining-app
    ports:
      - "80:8080"
    depends_on:
      - mysql
      - redis
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_REDIS_HOST=redis

  mysql:
    container_name: mysql
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=catch_dining

  redis:
    container_name: redis
    image: redis:7.0.14
    ports:
      - "6379:6379"
    restart: always
