spring:
  datasource:
    url: jdbc:mysql://write-db:3306/catch_dining?serverTimezone=UTC
    username: andy
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    read-db:
      url: jdbc:mysql://read-db:3306/catch_dining?serverTimezone=UTC
      username: andy
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: redis
    port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
      springframework:
        security: debug

jwt:
  secret: 5bc35db8b6c3725c3b1e767fbfccc78d6067abcdcb70fa3ce9973837351dab03
  alg: HS256
  access:
    exp: 900000
  refresh:
    exp: 3600000