CHANGE MASTER TO
    MASTER_HOST='write-db',
    MASTER_USER='repl',
    MASTER_PASSWORD='1234',
    MASTER_LOG_FILE='mysql-bin.000001',
    MASTER_LOG_POS=4,
    GET_MASTER_PUBLIC_KEY=1;
START SLAVE;